# Generated by Django 2.0.5 on 2018-05-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db2csv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depomiktar',
            name='id',
        ),
        migrations.AddField(
            model_name='depomiktar',
            name='girisid',
            field=models.AutoField(db_column='GIRISID', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
