# Generated by Django 2.0.5 on 2018-05-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db2csv', '0002_auto_20180517_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uetiket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urunad', models.CharField(max_length=60)),
                ('renk', models.CharField(blank=True, max_length=50, null=True)),
                ('beden', models.CharField(blank=True, max_length=50, null=True)),
                ('birim', models.CharField(blank=True, max_length=50, null=True)),
                ('toplammiktar', models.IntegerField(blank=True, null=True)),
                ('alisfiyati', models.FloatField(blank=True, null=True)),
                ('satisfiyati', models.FloatField(blank=True, null=True)),
                ('uruncinsi', models.CharField(blank=True, max_length=50, null=True)),
                ('firmakodu', models.IntegerField(blank=True, null=True)),
                ('barkod', models.CharField(max_length=50)),
                ('ikincisatfiyat', models.FloatField()),
                ('kkartli', models.FloatField()),
                ('iskonto', models.FloatField()),
                ('marka', models.CharField(blank=True, max_length=50, null=True)),
                ('sezon', models.CharField(blank=True, max_length=20, null=True)),
                ('eskifiyat1', models.FloatField(blank=True, null=True)),
                ('eskifiyat2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uetiket',
            },
        ),
    ]
