# Generated by Django 2.0.5 on 2018-05-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db2csv', '0003_uetiket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('urunno', models.AutoField(db_column='URUNNO', primary_key=True, serialize=False)),
                ('firmakodu', models.IntegerField(blank=True, null=True)),
                ('renk', models.CharField(blank=True, db_column='RENK', max_length=50, null=True)),
                ('beden', models.CharField(blank=True, db_column='BEDEN', max_length=50, null=True)),
                ('birim', models.CharField(blank=True, db_column='BIRIM', max_length=50, null=True)),
                ('uruncinsi', models.CharField(blank=True, db_column='URUNCINSI', max_length=50, null=True)),
                ('toplammiktar', models.FloatField(blank=True, db_column='TOPLAMMIKTAR', null=True)),
                ('tarih', models.DateField(blank=True, db_column='TARIH', null=True)),
                ('saat', models.TimeField(blank=True, db_column='SAAT', null=True)),
                ('alisfiyati', models.FloatField(blank=True, db_column='ALISFIYATI', null=True)),
                ('satisfiyati', models.FloatField(blank=True, db_column='SATISFIYATI', null=True)),
                ('toptanci', models.CharField(blank=True, db_column='TOPTANCI', max_length=75, null=True)),
                ('alistutari', models.FloatField(blank=True, db_column='ALISTUTARI', null=True)),
                ('satistutari', models.FloatField(blank=True, db_column='SATISTUTARI', null=True)),
                ('satistutari2', models.FloatField(blank=True, db_column='SATISTUTARI2', null=True)),
                ('satisfiyati2', models.FloatField(blank=True, db_column='SATISFIYATI2', null=True)),
                ('kdv', models.FloatField(blank=True, db_column='KDV', null=True)),
                ('risk', models.IntegerField(blank=True, db_column='RISK', null=True)),
                ('iskonto', models.FloatField(blank=True, db_column='ISKONTO', null=True)),
                ('urunadi', models.CharField(blank=True, db_column='URUNADI', max_length=100, null=True)),
                ('uyari', models.IntegerField(blank=True, db_column='UYARI', null=True)),
                ('barkod', models.CharField(blank=True, db_column='BARKOD', max_length=30, null=True)),
                ('kkartli', models.FloatField(blank=True, null=True)),
                ('marka', models.CharField(blank=True, max_length=50, null=True)),
                ('sezon', models.CharField(blank=True, max_length=50, null=True)),
                ('secili', models.CharField(blank=True, max_length=6, null=True)),
                ('urunkodu', models.CharField(blank=True, db_column='URUNKODU', max_length=15, null=True)),
                ('kdvsizfiyat', models.FloatField(blank=True, null=True)),
                ('plasiyer', models.CharField(blank=True, max_length=50, null=True)),
                ('eskifiyat1', models.FloatField(blank=True, null=True)),
                ('eskifiyat2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'urun',
            },
        ),
    ]
